In [1]:
from functions.functions_image_training import *
import tensorflow as tf
import timeit
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import random
%matplotlib inline

//anaconda/lib/python3.5/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)


In [2]:
mainfolder = '/Users/carsonlam/vp/quality_confirmed/'
rejects = '/Users/carsonlam/vp/rejects/'

In [3]:
img_dict, cat_list = classifier_folder_to_jpg_dict_list(mainfolder,rejects)

In [4]:
list_of_tuples = cat_list_to_list_of_tuples(img_dict, cat_list)
type(list_of_tuples)

list

In [5]:
list_of_tuples[4]

[array([ 1.,  0.,  0.]), 'High_Quality/17128_RE.jpg']

In [6]:
random.shuffle(list_of_tuples)
list_of_tuples[4]

[array([ 1.,  0.,  0.]), 'High_Quality/19546_RE.jpg']

In [25]:
start_time = timeit.default_timer()

############### INPUTS: including bacth size, list of tuples and image dictionary###########################
total_num = len(list_of_tuples)
classes = len(img_dict)
batch_size = 6
num_steps = int(total_num / batch_size)
single_input_shape = (450,450,3)
new_height,new_width,new_depth = single_input_shape

################ TENSOR FLOW #########################################
# TF variables
tensor_image = tf.placeholder("uint8", [None, None, 3])

#manipulations 
original_shape = tf.shape(tensor_image)
resized_image = tf.image.resize_images(tensor_image, new_height, new_width)
resized_shape = tf.shape(resized_image)

#initialization class for session running
model = tf.initialize_all_variables()
########################################################################

########## FOR TESTING ONLY #######################################
num_steps = 3


########## TRAINING LOOP #####################################################
with tf.Session() as session: 
    
    session.run(model)

########## ONE EPOCH #####################################################
    for step in range(num_steps):
        offset = (step * batch_size) % (total_num)
        start = offset
        end = offset + batch_size
        if total_num - end < batch_size:
            end += (total_num % batch_size)

#################################################################################

        training_labels = np.zeros((batch_size,classes))
        training_tensors = np.zeros((batch_size,*single_input_shape))

####### USE 'start' and 'end'#####################################
    ### HERE ################################################################
        i =0
        for j in range(start,end):

            cycle_image = mpimg.imread(mainfolder + list_of_tuples[j][1])
            
            print(np.amin(cycle_image),np.amax(cycle_image))

            Original_shape, Resized_image, Resized_shape = session.run([original_shape,resized_image,resized_shape], 
                                                           feed_dict={tensor_image: cycle_image})
            
            training_labels[i] =  list_of_tuples[j][0]
            training_tensors[i] = Resized_image/255
            
            i+=1
            print(Original_shape, Resized_shape, type(Resized_image))

                
        if step > 2:
            break 
        
#######################################################################################
    #print('step',step, 'from ',start, 'to ',end)
end_time = timeit.default_timer()
print('DONE, ran for %.2fm' % ((end_time - start_time) / 60.))

0 252
[441 619   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 206
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 225
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 113
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 198
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 148
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 239
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 191
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 163
[450 600   3] [450 450   3] <class 'numpy.ndarray'>
0 255
[450 600

In [21]:
single_input_shape = (450,450,3)
new_height,new_width,new_depth = single_input_shape
holder = np.zeros((4,*single_input_shape))

In [23]:
new_height

450